questions = {
    "what is the capital of france?": "Paris",
    "who wrote 'romeo and juliet'?": "William Shakespeare",
    "what is the largest planet in our solar system?": "Jupiter",
    "in which year did world war ii end?": "1945",
    "what is the currency of japan?": "Japanese Yen",
    "which element has the chemical symbol 'o'?": "Oxygen",
    "who is the current president of the united states?": "Joe Biden",
    "what is the powerhouse of the cell?": "Mitochondria",
    "in which year did the titanic sink?": "1912",
    "who painted the mona lisa?": "Leonardo da Vinci",
    "what is the square root of 64?": "8",
    "what is the speed of light?": "299,792 kilometers per second",
    "what is the national animal of australia?": "Red Kangaroo",
    "who wrote 'the great gatsby'?": "F. Scott Fitzgerald",
    "what is the capital of china?": "Beijing",
    "what is the largest ocean on earth?": "Pacific Ocean",
    "in what year did the first human land on the moon?": "1969",
    "who is known as the 'father of computer science'?": "Alan Turing",
    "what is the main ingredient in guacamole?": "Avocado",
    "which planet is known as the 'red planet'?": "Mars",
    "who discovered penicillin?": "Alexander Fleming",
    "what is the longest river in the world?": "Amazon River",
    "who painted the 'starry night'?": "Vincent van Gogh",
    "what is the chemical symbol for gold?": "Au",
    "what is the largest mammal in the world?": "Blue Whale"
}